name: 'Tiny Tapeout Install oss-cad-suite'
description: 'This action install oss-cad-suite Tiny Tapeout project'
branding:
  color: purple
  icon: book-open

inputs:
  token:
    description: 'A Github PAT, secrets.GITHUB_TOKEN for rate-limit avoidance'
    required: true

runs:
  using: 'composite'
  steps:
    - name: install oss-cad-suite
      uses: YosysHQ/setup-oss-cad-suite@v2
      with:
          python-override: true
          github-token: ${{ inputs.token }}

    - name: prepare oss-cad-suite
      shell: bash
      run: |
        [ -e /yosyshq ] || sudo ln -s $RUNNER_TEMP/oss-cad-suite /yosyshq || true

        if [ ! -e /yosyshq ]; then
          echo "WARNING: Unable to ensure setup of symlink /yosyshq, some things may not work as well as expected.  ln -s  $RUNNER_TEMP/oss-cad-suite /yosyshq" 1>&2
        fi

        echo "OSS_CAD_SUITE_HOME=$OSS_CAD_SUITE_HOME"
        test -n "$OSS_CAD_SUITE_HOME" || export OSS_CAD_SUITE_HOME="$RUNNER_TEMP/oss-cad-suite"
        echo "OSS_CAD_SUITE_HOME=$OSS_CAD_SUITE_HOME"
        echo "OSS_CAD_SUITE_HOME=$OSS_CAD_SUITE_HOME" >> $GITHUB_ENV

        if [ ! -e "$OSS_CAD_SUITE_HOME" ]; then
          echo "WARNING: \$OSS_CAD_SUITE_HOME not setup" 1>&2
        fi

        # Into system
        sudo -E apt-get install -y libffi7

        # Into oss-cad-suite
        source "$OSS_CAD_SUITE_HOME/environment"
        sudo -E python3 -m pip install coverage

        yosys --version
        iverilog -V
        cocotb-config --libpython
        cocotb-config --python-bin
        verilator --version
